excluded:
  - Pods
  - fastlane
  
disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - trailing_whitespace
 - vertical_whitespace
 - trailing_newline
 - mark
 - identifier_name
 
line_length:
  warning: 250
  error: 400
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true